### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by kzu** [pharring/ComponentDiagnostics#15]
🙏🙏🙏🙏

thanks!

Tried the typical unzipping of the VSIX straight to the Extensions folder, enabled it, but even if no exception is thrown, it hangs entirely: 

![image](https://user-images.githubusercontent.com/169707/142244165-dd0b3cd5-bbd7-4acb-93a5-1a79240f062f.png)

😢

**Comment by pharring** [comment]
I'll take a look.

**Comment by pharring** [comment]
Will publish the VS 2022 version manually

**Comment by pharring** [comment]
VS 2022 version published: https://marketplace.visualstudio.com/items?itemName=PaulHarrington.ComponentDiagnosticsDev17
